### ISSUE TITLE
Unusual definition of `gen-buffer`

### ISSUE THREAD

**Issue by wasamasa** [AlexCharlton/gl-utils#5]
Hello!  I've decided to take a look at this egg today for writing a simple OpenGL demo and found the following in `gl-utils-core.scm`:

```scheme
(define (gen-buffer)
  (let ((vec (make-u32vector 1)))
    (gl:gen-buffers 1 vec)
    (u32vector-ref vec 0)))
```

Is there a reason for this construct or can `let-location` be used instead just fine?

**Comment by AlexCharlton** [comment]
Hi! There's no particular reason for this other than the fact that I didn't know about locations when I wrote it.

I'd be skeptical that substituting in locations would provide any material gain other than some slightly cleaner code, but if you feel like leading the charge then PRs are welcome :)

**Comment by wasamasa** [comment]
Well, it makes it obvious that you're passing a pointer to an integer value.  Passing a SRFI-4 vector isn't nearly as obvious, especially the fact that they're passed as a pointer and its dereferenced value points to its first item.

**Comment by AlexCharlton** [comment]
`glGenBuffers` accepts an array of integers, so I'd argue that the code as is is keeping with the spirit of that method's signature. Still, unless one was is faster than another, I'd say they're both Good Enough.

**Comment by wasamasa** [comment]
Fair enough, I've only seen the single-element array version and assumed that you can't create more than one at a time.  Given that information, I can understand why you don't see any advantage in using locations.
